name: ngrouter
description: >
  Router for AngularDart.
  It enables navigation from one view to the next as users perform tasks.
version: 5.0.0-dev.1
repository: https://github.com/angulardart-community/angular

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  ngdart: ^8.0.0-dev.1
  web: ^1.1.1
dev_dependencies:
  async: ^2.10.0
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^4.1.3
  lints: ^5.0.0
  mockito: ^5.3.2
  ngtest: ^5.0.0-dev.1
  test: ^1.22.2
