# Extend the default sub-set of linter/analyzer rules used in google3.
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Permanent inclusions: These are optional hints that are not default on.
    unused_element: warning
    unused_field: warning
    unused_local_variable: warning

    # Permanent exclusions: Unlikely to removed.
    # =====================
    # Allow importing .template.dart files without an [explicit] analyzer error.
    uri_has_not_been_generated: ignore
    # Ignore our own deprecated symbols (too noisy).
    deprecated_member_use_from_same_package: ignore
    # Allow having TODOs in the code (too noisy).
    todo: ignore

    # Security exclusions: We are security reviewed separate from these lints.
    # =====================
    unsafe_html: ignore

    # Temporary exclusions: Can be removed in the future.
    # =====================
    # Re-enable once we no longer have 200+ analyzer related deprecations.
    deprecated_member_use: ignore
    # Re-enable this once unused parameters are exempted (e.g. callback(_) {}).
    inference_failure_on_untyped_parameter: ignore

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - use_full_hex_values_for_flutter_colors
