name: examples_hello_world

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  ngdart:

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.1.0
  lints: ^5.0.0
