name: goldens
description: Goldens for AngularDart.
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
#  js: ^0.7.2
  ngdart: ^8.0.0-dev.1

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^4.1.3
  dart_style: ^3.0.1
  glob: ^2.1.1
  lints: ^5.0.0
  path: ^1.8.3
