name: ngast
description: Parser and utilities for AngularDart templates
version: 3.0.0-dev.0
repository: https://github.com/angulardart-community/angular

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  charcode: ^1.3.1
  collection: ^1.17.0
  meta: ^1.8.0
  source_span: ^1.9.1
  string_scanner: ^1.2.0

dev_dependencies:
  lints: ^5.0.0
  path: ^1.8.3
  test: ^1.22.2
