name: ngcompiler
description: >
  The AngularDart compiler.
  It compiles your component files written in Dart into templates so that you
  don't have to worry about all the complicated hassle.
version: 4.0.0-dev.1
repository: https://github.com/angulardart-community/angular

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^7.3.0
  args: ^2.3.2
  build: ^2.3.1
  build_test: ^2.1.6
  code_builder: ^4.4.0
  collection: ^1.17.0
  csslib: ^1.0.0
  dart_style: ^3.0.1
  logging: ^1.1.0
  meta: ^1.8.0
  ngast: ^4.0.0-dev.1
  ngdart: ^9.0.0-dev.1
  package_config: ^2.1.0
  path: ^1.8.3
  source_gen: ^2.0.0
  source_span: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.22.2
