sdk:
  - 3.6.1
  - pubspec

stages:
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart run test -P vm
      - command: dart run build_runner test --fail-on-severe -- -P browser
