name: _tests
description: Tests for AngularDart.
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  build_resolvers: ^2.1.0
  build_test: ^2.1.6
  collection: ^1.17.0
  logging: ^1.3.0
  ngcompiler: ^4.0.0-dev.1
  ngdart: ^8.0.0-dev.1
  ngtest: ^5.0.0-dev.1
  test: ^1.22.2
  web: ^1.1.1

dev_dependencies:
  analyzer: ^7.3.0
  build_runner: ^2.3.3
  build_web_compilers: ^4.1.3
  csslib: ^1.0.0
  lints: ^5.0.0
  meta: ^1.8.0
  mockito: ^5.3.2
  package_config: ^2.1.0
  source_span: ^1.9.1
  term_glyph: ^1.2.1
