name: ngtest
description: >
  Testing runner and library for AngularDart.
  This package is necessary to write component tests for AngularDart components.
version: 6.0.0-dev.1
repository: https://github.com/angulardart-community/angular

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0
  ngdart: ^9.0.0-dev.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^4.1.3
  lints: ^5.0.0
  test: ^1.22.2
